# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contact_book.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'contact_book.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63ontact_book.proto\x12\x05\x63p117\"\x17\n\tContactId\x12\n\n\x02Id\x18\x01 \x01(\x05\"\'\n\x15\x44\x65leteContactResponse\x12\x0e\n\x06Result\x18\x01 \x01(\t\"Q\n\x06Person\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x14\n\x0c\x45nrollNumber\x18\x02 \x01(\x05\x12\x0e\n\x06Height\x18\x03 \x01(\x02\x12\x13\n\x0bLuckNumbers\x18\x04 \x03(\x05\x32\xbe\x01\n\x0f\x43ontactsManager\x12\x32\n\rCreateContact\x12\r.cp117.Person\x1a\x10.cp117.ContactId\"\x00\x12\x34\n\x0fRetrieveContact\x12\x10.cp117.ContactId\x1a\r.cp117.Person\"\x00\x12\x41\n\rDeleteContact\x12\x10.cp117.ContactId\x1a\x1c.cp117.DeleteContactResponse\"\x00\x42\x12\n\x0e\x63om.cp117.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contact_book_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016com.cp117.grpcP\001'
  _globals['_CONTACTID']._serialized_start=29
  _globals['_CONTACTID']._serialized_end=52
  _globals['_DELETECONTACTRESPONSE']._serialized_start=54
  _globals['_DELETECONTACTRESPONSE']._serialized_end=93
  _globals['_PERSON']._serialized_start=95
  _globals['_PERSON']._serialized_end=176
  _globals['_CONTACTSMANAGER']._serialized_start=179
  _globals['_CONTACTSMANAGER']._serialized_end=369
# @@protoc_insertion_point(module_scope)
