# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import contact_book_pb2 as contact__book__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in contact_book_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContactsManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateContact = channel.unary_unary(
                '/cp117.ContactsManager/CreateContact',
                request_serializer=contact__book__pb2.Person.SerializeToString,
                response_deserializer=contact__book__pb2.ContactId.FromString,
                _registered_method=True)
        self.RetrieveContact = channel.unary_unary(
                '/cp117.ContactsManager/RetrieveContact',
                request_serializer=contact__book__pb2.ContactId.SerializeToString,
                response_deserializer=contact__book__pb2.Person.FromString,
                _registered_method=True)
        self.DeleteContact = channel.unary_unary(
                '/cp117.ContactsManager/DeleteContact',
                request_serializer=contact__book__pb2.ContactId.SerializeToString,
                response_deserializer=contact__book__pb2.DeleteContactResponse.FromString,
                _registered_method=True)


class ContactsManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContactsManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateContact': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateContact,
                    request_deserializer=contact__book__pb2.Person.FromString,
                    response_serializer=contact__book__pb2.ContactId.SerializeToString,
            ),
            'RetrieveContact': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveContact,
                    request_deserializer=contact__book__pb2.ContactId.FromString,
                    response_serializer=contact__book__pb2.Person.SerializeToString,
            ),
            'DeleteContact': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteContact,
                    request_deserializer=contact__book__pb2.ContactId.FromString,
                    response_serializer=contact__book__pb2.DeleteContactResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cp117.ContactsManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cp117.ContactsManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContactsManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cp117.ContactsManager/CreateContact',
            contact__book__pb2.Person.SerializeToString,
            contact__book__pb2.ContactId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cp117.ContactsManager/RetrieveContact',
            contact__book__pb2.ContactId.SerializeToString,
            contact__book__pb2.Person.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cp117.ContactsManager/DeleteContact',
            contact__book__pb2.ContactId.SerializeToString,
            contact__book__pb2.DeleteContactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
