# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cperson.proto\x12\x04\x64\x65mo\"Q\n\x06Person\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x14\n\x0c\x45nrollNumber\x18\x02 \x01(\x05\x12\x0e\n\x06Height\x18\x03 \x01(\x01\x12\x13\n\x0bLuckNumbers\x18\x04 \x03(\x05\x42\x13\n\x04\x64\x65moB\x0bPersonProtob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'person_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\004demoB\013PersonProto'
  _PERSON._serialized_start=22
  _PERSON._serialized_end=103
# @@protoc_insertion_point(module_scope)
