// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package demo;

public final class PersonProto {
  private PersonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string Name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string Name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 EnrollNumber = 2;</code>
     * @return The enrollNumber.
     */
    int getEnrollNumber();

    /**
     * <code>double Height = 3;</code>
     * @return The height.
     */
    double getHeight();

    /**
     * <code>repeated int32 LuckNumbers = 4;</code>
     * @return A list containing the luckNumbers.
     */
    java.util.List<java.lang.Integer> getLuckNumbersList();
    /**
     * <code>repeated int32 LuckNumbers = 4;</code>
     * @return The count of luckNumbers.
     */
    int getLuckNumbersCount();
    /**
     * <code>repeated int32 LuckNumbers = 4;</code>
     * @param index The index of the element to return.
     * @return The luckNumbers at the given index.
     */
    int getLuckNumbers(int index);
  }
  /**
   * Protobuf type {@code demo.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
      luckNumbers_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Person();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return demo.PersonProto.internal_static_demo_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return demo.PersonProto.internal_static_demo_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              demo.PersonProto.Person.class, demo.PersonProto.Person.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string Name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string Name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENROLLNUMBER_FIELD_NUMBER = 2;
    private int enrollNumber_ = 0;
    /**
     * <code>int32 EnrollNumber = 2;</code>
     * @return The enrollNumber.
     */
    @java.lang.Override
    public int getEnrollNumber() {
      return enrollNumber_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 3;
    private double height_ = 0D;
    /**
     * <code>double Height = 3;</code>
     * @return The height.
     */
    @java.lang.Override
    public double getHeight() {
      return height_;
    }

    public static final int LUCKNUMBERS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList luckNumbers_;
    /**
     * <code>repeated int32 LuckNumbers = 4;</code>
     * @return A list containing the luckNumbers.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getLuckNumbersList() {
      return luckNumbers_;
    }
    /**
     * <code>repeated int32 LuckNumbers = 4;</code>
     * @return The count of luckNumbers.
     */
    public int getLuckNumbersCount() {
      return luckNumbers_.size();
    }
    /**
     * <code>repeated int32 LuckNumbers = 4;</code>
     * @param index The index of the element to return.
     * @return The luckNumbers at the given index.
     */
    public int getLuckNumbers(int index) {
      return luckNumbers_.getInt(index);
    }
    private int luckNumbersMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (enrollNumber_ != 0) {
        output.writeInt32(2, enrollNumber_);
      }
      if (java.lang.Double.doubleToRawLongBits(height_) != 0) {
        output.writeDouble(3, height_);
      }
      if (getLuckNumbersList().size() > 0) {
        output.writeUInt32NoTag(34);
        output.writeUInt32NoTag(luckNumbersMemoizedSerializedSize);
      }
      for (int i = 0; i < luckNumbers_.size(); i++) {
        output.writeInt32NoTag(luckNumbers_.getInt(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (enrollNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, enrollNumber_);
      }
      if (java.lang.Double.doubleToRawLongBits(height_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, height_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < luckNumbers_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(luckNumbers_.getInt(i));
        }
        size += dataSize;
        if (!getLuckNumbersList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        luckNumbersMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof demo.PersonProto.Person)) {
        return super.equals(obj);
      }
      demo.PersonProto.Person other = (demo.PersonProto.Person) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getEnrollNumber()
          != other.getEnrollNumber()) return false;
      if (java.lang.Double.doubleToLongBits(getHeight())
          != java.lang.Double.doubleToLongBits(
              other.getHeight())) return false;
      if (!getLuckNumbersList()
          .equals(other.getLuckNumbersList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ENROLLNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getEnrollNumber();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getHeight()));
      if (getLuckNumbersCount() > 0) {
        hash = (37 * hash) + LUCKNUMBERS_FIELD_NUMBER;
        hash = (53 * hash) + getLuckNumbersList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static demo.PersonProto.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static demo.PersonProto.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static demo.PersonProto.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static demo.PersonProto.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static demo.PersonProto.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static demo.PersonProto.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static demo.PersonProto.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static demo.PersonProto.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static demo.PersonProto.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static demo.PersonProto.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static demo.PersonProto.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static demo.PersonProto.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(demo.PersonProto.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.Person)
        demo.PersonProto.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return demo.PersonProto.internal_static_demo_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return demo.PersonProto.internal_static_demo_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                demo.PersonProto.Person.class, demo.PersonProto.Person.Builder.class);
      }

      // Construct using demo.PersonProto.Person.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        enrollNumber_ = 0;
        height_ = 0D;
        luckNumbers_ = emptyIntList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return demo.PersonProto.internal_static_demo_Person_descriptor;
      }

      @java.lang.Override
      public demo.PersonProto.Person getDefaultInstanceForType() {
        return demo.PersonProto.Person.getDefaultInstance();
      }

      @java.lang.Override
      public demo.PersonProto.Person build() {
        demo.PersonProto.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public demo.PersonProto.Person buildPartial() {
        demo.PersonProto.Person result = new demo.PersonProto.Person(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(demo.PersonProto.Person result) {
        if (((bitField0_ & 0x00000008) != 0)) {
          luckNumbers_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.luckNumbers_ = luckNumbers_;
      }

      private void buildPartial0(demo.PersonProto.Person result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.enrollNumber_ = enrollNumber_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.height_ = height_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof demo.PersonProto.Person) {
          return mergeFrom((demo.PersonProto.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(demo.PersonProto.Person other) {
        if (other == demo.PersonProto.Person.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getEnrollNumber() != 0) {
          setEnrollNumber(other.getEnrollNumber());
        }
        if (other.getHeight() != 0D) {
          setHeight(other.getHeight());
        }
        if (!other.luckNumbers_.isEmpty()) {
          if (luckNumbers_.isEmpty()) {
            luckNumbers_ = other.luckNumbers_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureLuckNumbersIsMutable();
            luckNumbers_.addAll(other.luckNumbers_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                enrollNumber_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 25: {
                height_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              case 32: {
                int v = input.readInt32();
                ensureLuckNumbersIsMutable();
                luckNumbers_.addInt(v);
                break;
              } // case 32
              case 34: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureLuckNumbersIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  luckNumbers_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string Name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string Name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string Name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int enrollNumber_ ;
      /**
       * <code>int32 EnrollNumber = 2;</code>
       * @return The enrollNumber.
       */
      @java.lang.Override
      public int getEnrollNumber() {
        return enrollNumber_;
      }
      /**
       * <code>int32 EnrollNumber = 2;</code>
       * @param value The enrollNumber to set.
       * @return This builder for chaining.
       */
      public Builder setEnrollNumber(int value) {
        
        enrollNumber_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 EnrollNumber = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnrollNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        enrollNumber_ = 0;
        onChanged();
        return this;
      }

      private double height_ ;
      /**
       * <code>double Height = 3;</code>
       * @return The height.
       */
      @java.lang.Override
      public double getHeight() {
        return height_;
      }
      /**
       * <code>double Height = 3;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(double value) {
        
        height_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>double Height = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000004);
        height_ = 0D;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList luckNumbers_ = emptyIntList();
      private void ensureLuckNumbersIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          luckNumbers_ = mutableCopy(luckNumbers_);
          bitField0_ |= 0x00000008;
        }
      }
      /**
       * <code>repeated int32 LuckNumbers = 4;</code>
       * @return A list containing the luckNumbers.
       */
      public java.util.List<java.lang.Integer>
          getLuckNumbersList() {
        return ((bitField0_ & 0x00000008) != 0) ?
                 java.util.Collections.unmodifiableList(luckNumbers_) : luckNumbers_;
      }
      /**
       * <code>repeated int32 LuckNumbers = 4;</code>
       * @return The count of luckNumbers.
       */
      public int getLuckNumbersCount() {
        return luckNumbers_.size();
      }
      /**
       * <code>repeated int32 LuckNumbers = 4;</code>
       * @param index The index of the element to return.
       * @return The luckNumbers at the given index.
       */
      public int getLuckNumbers(int index) {
        return luckNumbers_.getInt(index);
      }
      /**
       * <code>repeated int32 LuckNumbers = 4;</code>
       * @param index The index to set the value at.
       * @param value The luckNumbers to set.
       * @return This builder for chaining.
       */
      public Builder setLuckNumbers(
          int index, int value) {
        
        ensureLuckNumbersIsMutable();
        luckNumbers_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 LuckNumbers = 4;</code>
       * @param value The luckNumbers to add.
       * @return This builder for chaining.
       */
      public Builder addLuckNumbers(int value) {
        
        ensureLuckNumbersIsMutable();
        luckNumbers_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 LuckNumbers = 4;</code>
       * @param values The luckNumbers to add.
       * @return This builder for chaining.
       */
      public Builder addAllLuckNumbers(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureLuckNumbersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, luckNumbers_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 LuckNumbers = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLuckNumbers() {
        luckNumbers_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.Person)
    }

    // @@protoc_insertion_point(class_scope:demo.Person)
    private static final demo.PersonProto.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new demo.PersonProto.Person();
    }

    public static demo.PersonProto.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public demo.PersonProto.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\022\004demo\"Q\n\006Person\022\014\n\004Name\030\001" +
      " \001(\t\022\024\n\014EnrollNumber\030\002 \001(\005\022\016\n\006Height\030\003 \001" +
      "(\001\022\023\n\013LuckNumbers\030\004 \003(\005B\023\n\004demoB\013PersonP" +
      "rotob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_demo_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Person_descriptor,
        new java.lang.String[] { "Name", "EnrollNumber", "Height", "LuckNumbers", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
